version: '3.7'
services:
  mongodb:
    container_name: dock-mongodb
    image: mongo:latest
    network_mode: host
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: MONdb20
    volumes:
      - ./data:/data/db:rw
